import { doublePasswordCheck, checkEmail } from '../../../@core/utils/validators';

export const InstitutionUserConfig = {
  validator: doublePasswordCheck,
  paths: {
    editRedirect: '/system/institution-user/update/',
    readRedirect: '/system/institution-user/read/',
  },
  fields: {
    username: {
      creable: true,
      showable: true,
      editable: true,
      key: 'username',
      dataType: 'string',
      label: 'Username',
      inputType: 'text',
      inputName: 'username-input-name',
      formControlName: 'username-form-control-name',
      placeholder: 'joedoe',
      required: true,
    },
    email: {
      creable: true,
      showable: true,
      editable: true,
      key: 'email',
      dataType: 'string',
      label: 'Email',
      inputType: 'email',
      inputName: 'email-input-name',
      formControlName: 'email-form-control-name',
      placeholder: 'joedoe@example.com',
      validator: checkEmail,
      required: true,
    },
    password: {
      creable: true,
      showable: false,
      editable: false,
      key: 'password',
      dataType: 'string',
      label: 'Password',
      inputType: 'password',
      inputName: 'pasword-input-name',
      formControlName: 'pasword-form-control-name',
      placeholder: 'password',
      required: true,
    },
    password2: {
      creable: true,
      showable: false,
      editable: false,
      key: 'password2',
      dataType: 'string',
      label: 'Confirm Password',
      inputType: 'password',
      inputName: 'confirm-pasword-input-name',
      formControlName: 'confirm-pasword-form-control-name',
      placeholder: 'confirm password',
      required: true,
    },
    first_name: {
      creable: true,
      showable: true,
      editable: true,
      key: 'first_name',
      dataType: 'string',
      label: 'First name',
      inputType: 'text',
      inputName: 'first-name-input-name',
      formControlName: 'first-name-form-control-name',
      placeholder: 'Joe',
      required: true,
    },
    last_name: {
      creable: true,
      showable: true,
      editable: true,
      key: 'last_name',
      dataType: 'string',
      label: 'Last name',
      inputType: 'text',
      inputName: 'last-name-input-name',
      formControlName: 'last-name-form-control-name',
      placeholder: 'Doe',
    },
    // institution_id: {
    //   creable: true,
    //   showable: true,
    //   editable: false,
    //   key: 'institution_id',
    //   dataType: 'object',
    //   label: 'Institution',
    //   inputType: 'select-remote',
    //   search: 'search',
    //   optionLabelAccessor: 'name',
    //   optionValueAccessor: 'id',
    //   // apiService: ApiInstitutionService,
    //   inputName: 'institution-input-name',
    //   formControlName: 'institution-form-control-name',
    //   placeholder: 'uoc',
    //   // validator: () => Validators.required,
    // },
    uid: {
      creable: true,
      showable: true,
      editable: true,
      key: 'uid',
      dataType: 'string',
      label: 'UID',
      inputType: 'text',
      inputName: 'uid-input-name',
      formControlName: 'uid-form-control-name',
      placeholder: 'uid',
    },
    locale: {
      creable: true,
      showable: true,
      editable: true,
      key: 'locale',
      dataType: 'string',
      label: 'Language',
      inputType: 'select',
      options: [
        {
          value: 'en',
          key: 'en',
        },
        {
          value: 'es',
          key: 'es',
        },
        {
          value: 'ca',
          key: 'ca',
        },
        {
          value: 'bg',
          key: 'bg',
        },
        {
          value: 'fi',
          key: 'fi',
        },
        {
          value: 'tr',
          key: 'tr',
        },
      ],
      inputName: 'locale-input-name',
      formControlName: 'locale-form-control-name',
      placeholder: 'en',
      // required: true,
    },
    // is_staff: {
    //   creable: true,
    //   showable: true,
    //   editable: true,
    //   key: 'is_staff',
    //   dataType: 'string',
    //   label: 'GLOBAL_ADMIN',
    //   inputType: 'check-box',
    //   defaultValue: false,
    //   inputName: 'is_staff-input-name',
    //   formControlName: 'is_staff-form-control-name',
    //   required: false,
    // },
    inst_admin: {
      creable: true,
      showable: true,
      editable: true,
      key: 'inst_admin',
      dataType: 'boolean',
      label: 'ADMIN',
      inputType: 'check-box',
      defaultValue: false,
      inputName: 'inst_admin-input-name',
      formControlName: 'inst_admin-form-control-name',
      required: false,
    },
    send_admin: {
      creable: true,
      showable: true,
      editable: true,
      key: 'send_admin',
      dataType: 'boolean',
      label: 'SEND',
      inputType: 'check-box',
      defaultValue: false,
      inputName: 'send_admin-input-name',
      formControlName: 'send_admin-form-control-name',
      required: false,
    },
    legal_admin: {
      creable: true,
      showable: true,
      editable: true,
      key: 'legal_admin',
      dataType: 'boolean',
      label: 'LEGAL',
      inputType: 'check-box',
      defaultValue: false,
      inputName: 'legal_admin-input-name',
      formControlName: 'legal_admin-form-control-name',
      required: false,
    },
    data_admin: {
      creable: true,
      showable: true,
      editable: true,
      key: 'data_admin',
      dataType: 'boolean',
      label: 'DATA',
      inputType: 'check-box',
      defaultValue: false,
      inputName: 'data_admin-input-name',
      formControlName: 'data_admin-form-control-name',
      required: false,
    },
    login_allowed: {
      creable: true,
      showable: true,
      editable: true,
      key: 'login_allowed',
      dataType: 'boolean',
      label: 'Login allowed',
      inputType: 'check-box',
      defaultValue: false,
      inputName: 'login_allowed-input-name',
      formControlName: 'login_allowed-form-control-name',
      required: false,
    },
    // roles: {
    //   creable: true,
    //   showable: true,
    //   editable: true,
    //   key: 'roles',
    //   dataType: 'string',
    //   label: 'Roles',
    //   inputType: 'select-multiple',
    //   options: [
    //     {
    //       value: 'GLOBAL_ADMIN',
    //       key: 'GLOBAL_ADMIN',
    //     },
    //     {
    //       value: 'ADMIN',
    //       key: 'ADMIN',
    //     },
    //     {
    //       value: 'SEND',
    //       key: 'SEND',
    //     },
    //     {
    //       value: 'DATA_MANAGEMENT',
    //       key: 'DATA_MANAGEMENT',
    //     },
    //     {
    //       value: 'IC_MANAGEMENT',
    //       key: 'IC_MANAGEMENT',
    //     },
    //     {
    //       value: 'ACADEMIC_MANAGEMENT',
    //       key: 'ACADEMIC_MANAGEMENT',
    //     },
    //   ],
    //   inputName: 'roles-input-name',
    //   formControlName: 'roles-form-control-name',
    //   placeholder: 'en',
    //   // required: false,
    // },
  },
};
