export const CourseConfig = {
  validator: null,
  fields: {
    code: {
      key: 'code',
      creable: true,
      showable: true,
      editable: false,
      dataType: 'string',
      label: 'ENTITIES.COURSE.CODE',
      inputType: 'text',
      inputName: 'code-input-name',
      formControlName: 'code-form-control-name',
      required: true,
    },
    description: {
      key: 'description',
      creable: true,
      showable: true,
      editable: false,
      dataType: 'string',
      label: 'ENTITIES.COURSE.DESCRIPTION',
      inputType: 'text',
      inputName: 'description-input-name',
      formControlName: 'description-form-control-name',
      required: true,
    },
    start: {
      creable: true,
      showable: true,
      editable: false,
      key: 'start',
      dataType: 'dateTime',
      withTime: false,
      label: 'ENTITIES.COURSE.START',
      inputType: 'dateTime',
      inputName: 'start-input-name',
      formControlName: 'start-form-control-name',
    },
    end: {
      creable: true,
      showable: true,
      editable: false,
      key: 'end',
      dataType: 'dateTime',
      withTime: false,
      label: 'ENTITIES.COURSE.END',
      inputType: 'dateTime',
      inputName: 'end-input-name',
      formControlName: 'end-form-control-name',
    },
  },
};
