import { Validators } from '@angular/forms';

export const InstitutionIcConfig = {
  validator: null,
  fields: {
    // institution: {
    //   creable: true,
    //   showable: true,
    //   editable: true,
    //   key: 'institution',
    //   dataType: 'object',
    //   label: 'Institution',
    //   inputType: 'select-remote',
    //   search: 'search',
    //   optionLabelAccessor: 'name',
    //   optionValueAccessor: 'id',
    //   // apiService: ApiInstitutionService,
    //   inputName: 'institution-input-name',
    //   formControlName: 'institution-form-control-name',
    //   placeholder: 'uoc',
    //   validator: () => Validators.required,
    // },
    version: {
      key: 'version',
      creable: true,
      showable: true,
      editable: false,
      dataType: 'string',
      label: 'VERSION',
      inputType: 'text',
      inputName: 'version-input-name',
      formControlName: 'version-form-control-name',
      placeholder: '0.1.2',
      required: true,
    },
    valid_from: {
      creable: true,
      showable: true,
      editable: false,
      key: 'valid_from',
      dataType: 'dateTime',
      withTime: false,
      label: 'VALID_FROM',
      inputType: 'dateTime',
      inputName: 'valid-from-input-name',
      formControlName: 'valid-from-form-control-name',
      // placeholder: 'Doe',
    },
    file: {
      creable: false,
      showable: true,
      editable: true,
      key: 'file',
      dataType: 'string',
      label: 'Upload PDF file',
      inputType: 'file',
      inputName: 'upload-pdf-input-name',
      formControlName: 'upload-pdf-form-control-name',
      placeholder: 'Doe',
    },
    html: {
      creable: false,
      showable: true,
      editable: true,
      key: 'html',
      dataType: 'string',
      label: 'Html',
      inputType: 'html',
      inputName: 'html-input-name',
      formControlName: 'html-form-control-name',
      placeholder: 'joedoe@example.com',
      validator: 'html',
      required: true,
    },
  },
};
