stages:
  - quality
  - test
  - build
  - deploy

lint:
  stage: quality
  image: trion/ng-cli-karma:9.1.7
  allow_failure: false
  before_script:
    - npm i
  script:
    - ng lint

test:karma:
  stage: test
  image: trion/ng-cli-karma:9.1.7
  allow_failure: false
  before_script:
    - npm i
  script:
    - ng test --code-coverage --progress false --watch false
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  artifacts:
    paths:
      - coverage/

docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:18.09-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" -f docker/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE":latest
  only:
    - master

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:18.09-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" -f docker/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

deploy-demo:
  stage: deploy
  tags: 
    - tesla-ce-demo-deploy
  script:
    -  sudo /opt/tesla-ce/upgrade_core_images.sh
  only:
    - master

