export const AdminInstrumentProviderConfig = {
  paths: {},
  fields: {
    name: {
        creable: true,
        showable: true,
        editable: true,
        key: 'name',
        dataType: 'string',
        label: 'Name',
        inputType: 'text',
        inputName: 'name-input-name',
        formControlName: 'name-form-control-name',
        placeholder: 'instrument name',
        required: false,
    },
    acronym: {
        creable: true,
        showable: true,
        editable: true,
        key: 'acronym',
        dataType: 'string',
        label: 'Acronym',
        inputType: 'text',
        inputName: 'acronym-input-name',
        formControlName: 'acronym-form-control-name',
        placeholder: 'acronym',
        required: false,
    },
    version: {
        creable: true,
        showable: true,
        editable: true,
        key: 'version',
        dataType: 'string',
        label: 'Version',
        inputType: 'text',
        inputName: 'version-input-name',
        formControlName: 'version-form-control-name',
        placeholder: 'version',
        required: false,
    },
    description: {
        creable: true,
        showable: true,
        editable: true,
        key: 'description',
        dataType: 'string',
        label: 'Description',
        inputType: 'text',
        inputName: 'description-input-name',
        formControlName: 'description-form-control-name',
        placeholder: 'description',
        required: false,
    },
    queue: {
        creable: true,
        showable: true,
        editable: true,
        key: 'queue',
        dataType: 'string',
        label: 'Queue',
        inputType: 'text',
        inputName: 'queue-input-name',
        formControlName: 'queue-form-control-name',
        placeholder: 'queue',
        required: false,
    },
    url: {
        creable: true,
        showable: true,
        editable: true,
        key: 'url',
        dataType: 'string',
        label: 'Url',
        inputType: 'text',
        inputName: 'url-input-name',
        formControlName: 'url-form-control-name',
        placeholder: 'url',
        required: false,
    },
    options_schema: {
        creable: true,
        showable: true,
        editable: true,
        key: 'options_schema',
        dataType: 'json',
        label: 'Options Schema',
        inputType: 'textarea',
        inputName: 'options_schema-input-name',
        formControlName: 'options_schema-form-control-name',
        placeholder: 'json-forms schema',
        required: false,
    },
    options: {
        creable: true,
        showable: true,
        editable: true,
        key: 'options',
        dataType: 'json',
        label: 'Options',
        inputType: 'textarea',
        inputName: 'options-input-name',
        formControlName: 'options-form-control-name',
        placeholder: 'options',
        required: false,
    },
    image: {
        creable: true,
        showable: true,
        editable: true,
        key: 'image',
        dataType: 'string',
        label: 'Image',
        inputType: 'text',
        inputName: 'image-input-name',
        formControlName: 'image-form-control-name',
        placeholder: 'image',
        required: false,
    },
    service_port: {
        creable: true,
        showable: true,
        editable: true,
        key: 'service_port',
        dataType: 'string',
        label: 'Service port',
        inputType: 'text',
        inputName: 'service_port-input-name',
        formControlName: 'service_port-form-control-name',
        placeholder: 'service_port',
        required: false,
    },
    credentials: {
        creable: true,
        showable: true,
        editable: true,
        key: 'credentials',
        dataType: 'string',
        label: 'Credentials',
        inputType: 'textarea',
        inputName: 'credentials-input-name',
        formControlName: 'credentials-form-control-name',
        placeholder: 'credentials',
        required: false,
    },
    enabled: {
        creable: true,
        showable: true,
        editable: true,
        key: 'enabled',
        dataType: 'string',
        label: 'Enabled',
        inputType: 'check-box',
        defautlValue: false,
        inputName: 'enabled-input-name',
        formControlName: 'enabled-form-control-name',
        required: false,
    },
    allow_validation: {
        creable: true,
        showable: true,
        editable: true,
        key: 'allow_validation',
        dataType: 'string',
        label: 'Allow validation',
        inputType: 'check-box',
        defautlValue: false,
        inputName: 'allow_validation-input-name',
        formControlName: 'allow_validation-form-control-name',
        required: false,
    },
    inverted_polarity: {
        creable: true,
        showable: true,
        editable: true,
        key: 'inverted_polarity',
        dataType: 'string',
        label: 'Inverted polarity',
        inputType: 'check-box',
        defautlValue: false,
        inputName: 'inverted_polarity-input-name',
        formControlName: 'inverted_polarity-form-control-name',
        required: false,
    },
    has_service: {
        creable: true,
        showable: true,
        editable: true,
        key: 'has_service',
        dataType: 'string',
        label: 'Has service',
        inputType: 'check-box',
        defautlValue: false,
        inputName: 'has_service-input-name',
        formControlName: 'has_service-form-control-name',
        required: false,
    },
    validation_active: {
        creable: true,
        showable: true,
        editable: true,
        key: 'validation_active',
        dataType: 'string',
        label: 'Validation active',
        inputType: 'check-box',
        defautlValue: false,
        inputName: 'validation_active-input-name',
        formControlName: 'validation_active-form-control-name',
        required: false,
    },
  },
};
