export const InstitutionIcConfig = {
  fields: {
      institution: {
        key: 'institution',
        dataType: 'string',
        label: 'Institution',
        inputType: 'text',
        inputName: 'institution-input-name',
        formControlName: 'institution-form-control-name',
        placeholder: 'joedoe',
        defaultValue: 'UOC',
        disabled: true,
      },
      version: {
        key: 'version',
        dataType: 'string',
        label: 'Version',
        inputType: 'text',
        inputName: 'version-input-name',
        formControlName: 'version-form-control-name',
        placeholder: '0.1.2',
        required: true,
      },
      file: {
        key: 'file',
        dataType: 'string',
        label: 'Upload PDF file',
        inputType: 'file',
        inputName: 'upload-pdf-input-name',
        formControlName: 'upload-pdf-form-control-name',
        placeholder: 'Doe',
      },
      html: {
        key: 'html',
        dataType: 'string',
        label: 'Html',
        inputType: 'html',
        inputName: 'html-input-name',
        formControlName: 'html-form-control-name',
        placeholder: 'joedoe@example.com',
        validator: 'html',
        required: true,
      },
    },
};
