import { checkEmail, doublePasswordCheck } from '../../../@core/utils/validators';

export const AdminUserConfig = {
  validator: doublePasswordCheck,
  paths: {
    editRedirect: '/system/admin-user/update/',
    readRedirect: '/system/admin-user/read/',
  },
  fields: {
    username: {
      creable: true,
      showable: true,
      editable: true,
      key: 'username',
      dataType: 'string',
      label: 'ENTITIES.USER.USERNAME',
      inputType: 'text',
      inputName: 'username-input-name',
      formControlName: 'username-form-control-name',
      placeholder: 'joedoe',
      required: true,
    },
    email: {
      creable: true,
      showable: true,
      editable: true,
      key: 'email',
      dataType: 'string',
      label: 'ENTITIES.USER.EMAIL',
      inputType: 'email',
      inputName: 'email-input-name',
      formControlName: 'email-form-control-name',
      placeholder: 'joedoe@example.com',
      validator: checkEmail,
      required: true,
    },
    password: {
      creable: true,
      showable: false,
      editable: false,
      key: 'password',
      dataType: 'string',
      label: 'ENTITIES.USER.PASSWORD',
      inputType: 'password',
      inputName: 'pasword-input-name',
      formControlName: 'pasword-form-control-name',
      placeholder: 'password',
      required: true,
    },
    password2: {
      creable: true,
      showable: false,
      editable: false,
      key: 'password2',
      dataType: 'string',
      label: 'ENTITIES.USER.CONFIRM_PASSWORD',
      inputType: 'password',
      inputName: 'confirm-pasword-input-name',
      formControlName: 'confirm-pasword-form-control-name',
      placeholder: 'confirm password',
      required: true,
    },
    first_name: {
      creable: true,
      showable: true,
      editable: true,
      key: 'first_name',
      dataType: 'string',
      label: 'ENTITIES.USER.FIRST_NAME',
      inputType: 'text',
      inputName: 'first-name-input-name',
      formControlName: 'first-name-form-control-name',
      placeholder: 'Joe',
    },
    last_name: {
      creable: true,
      showable: true,
      editable: true,
      key: 'last_name',
      dataType: 'string',
      label: 'ENTITIES.USER.LAST_NAME',
      inputType: 'text',
      inputName: 'last-name-input-name',
      formControlName: 'last-name-form-control-name',
      placeholder: 'Doe',
    },
    institution_id: {
      creable: true,
      showable: true,
      editable: false,
      key: 'institution_id',
      dataType: 'object',
      label: 'ENTITIES.USER.INSTITUTION',
      inputType: 'select-remote',
      search: 'search',
      optionLabelAccessor: 'name',
      optionValueAccessor: 'id',
      inputName: 'institution-input-name',
      formControlName: 'institution-form-control-name',
      placeholder: 'uoc', 
    },
    uid: {
      creable: true,
      showable: true,
      editable: true,
      key: 'uid',
      dataType: 'string',
      label: 'ENTITIES.USER.UID',
      inputType: 'text',
      inputName: 'uid-input-name',
      formControlName: 'uid-form-control-name',
      placeholder: 'uid',
    },
    is_staff: {
      creable: true,
      showable: true,
      editable: true,
      key: 'is_staff',
      dataType: 'boolean',
      label: 'ENTITIES.USER.GLOBAL_ADMIN',
      inputType: 'check-box',
      defaultValue: false,
      inputName: 'is_staff-input-name',
      formControlName: 'is_staff-form-control-name',
      required: false,
    },
    inst_admin: {
      creable: true,
      showable: true,
      editable: true,
      key: 'inst_admin',
      dataType: 'boolean',
      label: 'ENTITIES.USER.ADMIN',
      inputType: 'check-box',
      defaultValue: false,
      inputName: 'inst_admin-input-name',
      formControlName: 'inst_admin-form-control-name',
      required: false,
    },
    send_admin: {
      creable: true,
      showable: true,
      editable: true,
      key: 'send_admin',
      dataType: 'boolean',
      label: 'ENTITIES.USER.SEND',
      inputType: 'check-box',
      defaultValue: false,
      inputName: 'send_admin-input-name',
      formControlName: 'send_admin-form-control-name',
      required: false,
    },
    legal_admin: {
      creable: true,
      showable: true,
      editable: true,
      key: 'legal_admin',
      dataType: 'boolean',
      label: 'ENTITIES.USER.LEGAL',
      inputType: 'check-box',
      defaultValue: false,
      inputName: 'legal_admin-input-name',
      formControlName: 'legal_admin-form-control-name',
      required: false,
    },
    data_admin: {
      creable: true,
      showable: true,
      editable: true,
      key: 'data_admin',
      dataType: 'boolean',
      label: 'ENTITIES.USER.DATA',
      inputType: 'check-box',
      defaultValue: false,
      inputName: 'data_admin-input-name',
      formControlName: 'data_admin-form-control-name',
      required: false,
    },
    login_allowed: {
      creable: true,
      showable: true,
      editable: true,
      key: 'login_allowed',
      dataType: 'boolean',
      label: 'ENTITIES.USER.LOGIN_ALLOWED',
      inputType: 'check-box',
      defaultValue: false,
      inputName: 'login_allowed-input-name',
      formControlName: 'login_allowed-form-control-name',
      required: false,
    },
  },
};
