export const AdminInstrumentConfig = {
  paths: {
    editRedirect: '/system/admin-instrument/update/',
    readRedirect: '/system/admin-instrument/read/',
  },
  validator: null,
  fields: {
    name: {
        creable: true,
        showable: true,
        editable: true,
        key: 'name',
        dataType: 'string',
        label: 'ENTITIES.INSTRUMENT.NAME',
        inputType: 'text',
        inputName: 'name-input-name',
        formControlName: 'name-form-control-name',
        placeholder: 'instrument name',
        required: false,
    },
    acronym: {
        creable: true,
        showable: true,
        editable: true,
        key: 'acronym',
        dataType: 'string',
        label: 'ENTITIES.INSTRUMENT.ACRONYM',
        inputType: 'text',
        inputName: 'acronym-input-name',
        formControlName: 'acronym-form-control-name',
        placeholder: 'instrument acronym',
        required: false,
    },
    description: {
        creable: true,
        showable: true,
        editable: true,
        key: 'description',
        dataType: 'string',
        label: 'ENTITIES.INSTRUMENT.DESCRIPTION',
        inputType: 'textarea',
        inputName: 'description-input-name',
        formControlName: 'description-form-control-name',
        placeholder: 'description',
        required: false,
    },
    queue: {
        creable: true,
        showable: true,
        editable: true,
        key: 'queue',
        dataType: 'string',
        label: 'ENTITIES.INSTRUMENT.QUEUE',
        inputType: 'text',
        inputName: 'queue-input-name',
        formControlName: 'queue-form-control-name',
        placeholder: 'instrument queue',
        required: false,
    },
    options_schema: {
        creable: true,
        showable: true,
        editable: true,
        key: 'options_schema',
        dataType: 'json',
        label: 'ENTITIES.INSTRUMENT.OPTIONS_SCHEMA',
        inputType: 'textarea',
        inputName: 'options_schema-input-name',
        formControlName: 'options_schema-form-control-name',
        placeholder: 'json-forms schema',
        required: false,
      },
    enabled: {
        creable: true,
        showable: true,
        editable: true,
        key: 'enabled',
        dataType: 'string',
        label: 'ENTITIES.INSTRUMENT.ENABLED',
        inputType: 'check-box',
        defaultValue: false,
        inputName: 'enabled-input-name',
        formControlName: 'enabled-form-control-name',
        placeholder: 'instrument enabled',
        required: false,
    },
    requires_enrolment: {
        creable: true,
        showable: true,
        editable: true,
        key: 'requires_enrolment',
        dataType: 'string',
        label: 'ENTITIES.INSTRUMENT.REQUIRES_ENROLMENT',
        inputType: 'check-box',
        defaultValue: false,
        inputName: 'requires_enrolment-input-name',
        formControlName: 'requires_enrolment-form-control-name',
        placeholder: 'instrument requires_enrolment',
        required: false,
    },
    identity: {
        creable: true,
        showable: true,
        editable: true,
        key: 'identity',
        dataType: 'string',
        label: 'ENTITIES.INSTRUMENT.IDENTITY',
        inputType: 'check-box',
        defaultValue: false,
        inputName: 'identity-input-name',
        formControlName: 'identity-form-control-name',
        placeholder: 'instrument identity',
        required: false,
    },
    originality: {
        creable: true,
        showable: true,
        editable: true,
        key: 'originality',
        dataType: 'string',
        label: 'ENTITIES.INSTRUMENT.ORIGINALITY',
        inputType: 'check-box',
        defaultValue: false,
        inputName: 'originality-input-name',
        formControlName: 'originality-form-control-name',
        placeholder: 'instrument originality',
        required: false,
    },
    authorship: {
        creable: true,
        showable: true,
        editable: true,
        key: 'authorship',
        dataType: 'string',
        label: 'ENTITIES.INSTRUMENT.AUTHORSHIP',
        inputType: 'check-box',
        defaultValue: false,
        inputName: 'authorship-input-name',
        formControlName: 'authorship-form-control-name',
        placeholder: 'instrument authorship',
        required: false,
    },
    integrity: {
        creable: true,
        showable: true,
        editable: true,
        key: 'integrity',
        dataType: 'string',
        label: 'ENTITIES.INSTRUMENT.INTEGRITY',
        inputType: 'check-box',
        defaultValue: false,
        inputName: 'integrity-input-name',
        formControlName: 'integrity-form-control-name',
        placeholder: 'instrument integrity',
        required: false,
    },
  },
};
