import { doublePasswordCheck, checkEmail } from '../../../@core/utils/validators';

export const AdminInstrumentConfig = {
  validator: doublePasswordCheck,
  paths: {
    editRedirect: '/system/admin-instrument/update/',
    readRedirect: '/system/admin-instrument/read/',
  },
  fields: {
    name: {
        creable: true,
        showable: true,
        editable: true,
        key: 'name',
        dataType: 'string',
        label: 'Name',
        inputType: 'text',
        inputName: 'name-input-name',
        formControlName: 'name-form-control-name',
        placeholder: 'instrument name',
        required: false,
    },
    acronym: {
        creable: true,
        showable: true,
        editable: true,
        key: 'acronym',
        dataType: 'string',
        label: 'Acronym',
        inputType: 'text',
        inputName: 'acronym-input-name',
        formControlName: 'acronym-form-control-name',
        placeholder: 'instrument acronym',
        required: false,
    },
    description: {
        creable: true,
        showable: true,
        editable: true,
        key: 'description',
        dataType: 'string',
        label: 'Description',
        inputType: 'textarea',
        inputName: 'description-input-name',
        formControlName: 'description-form-control-name',
        placeholder: 'description',
        required: false,
    },
    queue: {
        creable: true,
        showable: true,
        editable: true,
        key: 'queue',
        dataType: 'string',
        label: 'Queue',
        inputType: 'text',
        inputName: 'queue-input-name',
        formControlName: 'queue-form-control-name',
        placeholder: 'instrument queue',
        required: false,
    },
    options_schema: {
        creable: true,
        showable: true,
        editable: true,
        key: 'options_schema',
        dataType: 'string',
        label: 'Options Schema',
        inputType: 'textarea',
        inputName: 'options_schema-input-name',
        formControlName: 'options_schema-form-control-name',
        placeholder: 'json-forms schema',
        required: false,
      },
    enabled: {
        creable: true,
        showable: true,
        editable: true,
        key: 'enabled',
        dataType: 'string',
        label: 'Enabled',
        inputType: 'check-box',
        inputName: 'enabled-input-name',
        formControlName: 'enabled-form-control-name',
        placeholder: 'instrument enabled',
        required: false,
    },
    requires_enrolment: {
        creable: true,
        showable: true,
        editable: true,
        key: 'requires_enrolment',
        dataType: 'string',
        label: 'Requires Enrolment',
        inputType: 'check-box',
        inputName: 'requires_enrolment-input-name',
        formControlName: 'requires_enrolment-form-control-name',
        placeholder: 'instrument requires_enrolment',
        required: false,
    },
    identity: {
        creable: true,
        showable: true,
        editable: true,
        key: 'identity',
        dataType: 'string',
        label: 'Identity',
        inputType: 'check-box',
        inputName: 'identity-input-name',
        formControlName: 'identity-form-control-name',
        placeholder: 'instrument identity',
        required: false,
    },
    originality: {
        creable: true,
        showable: true,
        editable: true,
        key: 'originality',
        dataType: 'string',
        label: 'Originality',
        inputType: 'check-box',
        inputName: 'originality-input-name',
        formControlName: 'originality-form-control-name',
        placeholder: 'instrument originality',
        required: false,
    },
    authorship: {
        creable: true,
        showable: true,
        editable: true,
        key: 'authorship',
        dataType: 'string',
        label: 'Authorship',
        inputType: 'check-box',
        inputName: 'authorship-input-name',
        formControlName: 'authorship-form-control-name',
        placeholder: 'instrument authorship',
        required: false,
    },
    integrity: {
        creable: true,
        showable: true,
        editable: true,
        key: 'integrity',
        dataType: 'string',
        label: 'Integrity',
        inputType: 'check-box',
        inputName: 'integrity-input-name',
        formControlName: 'integrity-form-control-name',
        placeholder: 'instrument integrity',
        required: false,
    },
  },
};
