import { NbMenuItem } from '@nebular/theme';

export const MENU_ITEMS: NbMenuItem[] = [
  {
    title: 'Dashboard',
    icon: 'home-outline',
    link: '/dashboard',
  },
  {
      title: 'My Courses',
      icon: 'home-outline',
      link: '/my-courses',
  },
  {
      title: 'Test page',
      icon: 'home-outline',
      link: '/test-page',
  },
  {
      title: 'Administration',
      icon: 'home-outline',
      link: '/administration',
      children: [
          {
              title: 'Users',
              icon: 'home-outline',
              link: '/administration/users',
          },
          {
              title: 'Informed Consent',
              icon: 'home-outline',
              link: '/institution/institution-ic',
          },
          {
              title: 'SEND',
              icon: 'home-outline',
              link: '/administration/send',
          },
          {
              title: 'Courses',
              icon: 'home-outline',
              link: '/administration/courses',
          },
          {
              title: 'Data Management',
              icon: 'home-outline',
              link: '/administration/data-management',
          },
          {
              title: 'Settings',
              icon: 'home-outline',
              link: '/administration/settings',
          },
      ],
  },
  {
      title: 'Statistics',
      icon: 'home-outline',
      link: '/statistics',
  },
  {
      title: 'Monitoring',
      icon: 'home-outline',
      link: '/monitoring',
  },
  {
    title: 'System',
    icon: 'home-outline',
    link: '/system',
    children: [
        {
            title: 'Users',
            icon: 'home-outline',
            link: '/admin/admin-user',
        },
        {
            title: 'Institutions',
            icon: 'home-outline',
            link: '/system/institutions',
        },
        {
            title: 'Instruments',
            icon: 'home-outline',
            link: '/system/instruments',
        },
        {
            title: 'Services',
            icon: 'home-outline',
            link: '/system/services',
        },
        {
            title: 'Status',
            icon: 'home-outline',
            link: '/system/status',
        },
    ],
  },
];

export const SideMenuPermissions = {
  'dashboard': {
    'learner': true,
    'instructor': true,
    'admin': true,
    'ic_manager': true,
    'data_manager': true,
    'send_manager': true,
    'send_assigner': true,
    'academic_manager': true,
    'global_admin': true,
  },
  'my-courses': {
    'learner': true,
    'instructor': true,
    'admin': true,
    'ic_manager': true,
    'data_manager': true,
    'send_manager': true,
    'send_assigner': true,
    'academic_manager': true,
    'global_admin': true,
  },
  'test-page': {
    'learner': true,
    'instructor': true,
    'admin': true,
    'ic_manager': true,
    'data_manager': true,
    'send_manager': true,
    'send_assigner': true,
    'academic_manager': true,
    'global_admin': true,
  },
  'administration': {
    'dashboard': {
      'learner': true,
      'instructor': true,
      'admin': true,
      'ic_manager': true,
      'data_manager': true,
      'send_manager': true,
      'send_assigner': true,
      'academic_manager': true,
      'global_admin': true,
    },
    'users': {
        'learner': true,
        'instructor': true,
        'admin': true,
        'ic_manager': true,
        'data_manager': true,
        'send_manager': true,
        'send_assigner': true,
        'academic_manager': true,
        'global_admin': true,
    },
    'informed-consent': {
        'learner': true,
        'instructor': true,
        'admin': true,
        'ic_manager': true,
        'data_manager': true,
        'send_manager': true,
        'send_assigner': true,
        'academic_manager': true,
        'global_admin': true,
    },
    'send': {
        'learner': true,
        'instructor': true,
        'admin': true,
        'ic_manager': true,
        'data_manager': true,
        'send_manager': true,
        'send_assigner': true,
        'academic_manager': true,
        'global_admin': true,
    },
    'courses': {
        'learner': true,
        'instructor': true,
        'admin': true,
        'ic_manager': true,
        'data_manager': true,
        'send_manager': true,
        'send_assigner': true,
        'academic_manager': true,
        'global_admin': true,
    },
    'data-management': {
        'learner': true,
        'instructor': true,
        'admin': true,
        'ic_manager': true,
        'data_manager': true,
        'send_manager': true,
        'send_assigner': true,
        'academic_manager': true,
        'global_admin': true,
    },
  },
  'settings': {
    'learner': true,
    'instructor': true,
    'admin': true,
    'ic_manager': true,
    'data_manager': true,
    'send_manager': true,
    'send_assigner': true,
    'academic_manager': true,
    'global_admin': true,
  },
  'statistics': {
    'learner': true,
    'instructor': true,
    'admin': true,
    'ic_manager': true,
    'data_manager': true,
    'send_manager': true,
    'send_assigner': true,
    'academic_manager': true,
    'global_admin': true,
  },
  'monitoring': {
    'learner': true,
    'instructor': true,
    'admin': true,
    'ic_manager': true,
    'data_manager': true,
    'send_manager': true,
    'send_assigner': true,
    'academic_manager': true,
    'global_admin': true,
  },
  'system': {
    'dashboard': {
        'learner': true,
        'instructor': true,
        'admin': true,
        'ic_manager': true,
        'data_manager': true,
        'send_manager': true,
        'send_assigner': true,
        'academic_manager': true,
        'global_admin': true,
    },
    'users': {
        'learner': true,
        'instructor': true,
        'admin': true,
        'ic_manager': true,
        'data_manager': true,
        'send_manager': true,
        'send_assigner': true,
        'academic_manager': true,
        'global_admin': true,
    },
    'institutions': {
        'learner': true,
        'instructor': true,
        'admin': true,
        'ic_manager': true,
        'data_manager': true,
        'send_manager': true,
        'send_assigner': true,
        'academic_manager': true,
        'global_admin': true,
    },
    'instruments': {
        'learner': true,
        'instructor': true,
        'admin': true,
        'ic_manager': true,
        'data_manager': true,
        'send_manager': true,
        'send_assigner': true,
        'academic_manager': true,
        'global_admin': true,
    },
    'services': {
        'learner': true,
        'instructor': true,
        'admin': true,
        'ic_manager': true,
        'data_manager': true,
        'send_manager': true,
        'send_assigner': true,
        'academic_manager': true,
        'global_admin': true,
    },
    'status': {
        'learner': true,
        'instructor': true,
        'admin': true,
        'ic_manager': true,
        'data_manager': true,
        'send_manager': true,
        'send_assigner': true,
        'academic_manager': true,
        'global_admin': true,
    },
  },
};
